### PR TITLE
refactor: removed unused exceptions

### PR DESCRIPTION
**Pull request by sfat**
- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk-maven-plugin/blob/master/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

 #### What does this PR do?
Removed some unnecessary exceptions in the methods declarations
 #### Where should the reviewer start?

 #### How should this be manually tested?

 #### Any background context you want to provide?

 #### What are the relevant tickets?

 #### Screenshots

 #### Additional questions

### CODE REVIEW

**Comment by sfat** [comment]
I saw it failed while running locally the project. I also went and ran the tests against master, before doing any changes. 
Seems that it does not match what `verify.bsh` is trying to catch in the logs. After I ran them a few more times it seems that it was running successfully.
Is this a known issue? Maybe flaky tests?
In regards for my changes, I don't think it would affect in such a way that it would make the tests fail.

**Comment by sfat** [comment]
Any help would be much appreciated. I'm kinda stuck at the moment. I am not able to reproduce this locally as I don't have access to the `build.log` from travis

**Comment by sfat** [comment]
@ArturSnyk , can someone assist me, please?
It’s almost 1 month and nobody is saying anything.

**Comment by yuliabaron** [comment]
I think it fails as you're not a member of a Snyk org. I'll take over

**Comment by sfat** [comment]
@yuliabaron isn’t there a way to create an org just for the open source repositories?
It’s not really encouraging for people to contribute to your open source projects since we would bump into this issue every time.

**Comment by yuliabaron** [comment]
It's about the fact our org has an access to the secrets we use to build and test our projects (which is exactly why the test failed). I'll check if there's anything we could do about it.

**Comment by sfat** [comment]
@yuliabaron any update?

**Comment by yuliabaron** [comment]
Update about merge? Or the way we build the plugin?

**Comment by sfat** [comment]
Well, about the merge if you found a way that other people outside the org can create a PR without the build failing

**Comment by yuliabaron** [comment]
It will take time. For now, you can open a PR on a side branch and tag us on it.

**Comment by lili2311** [comment]
https://github.com/snyk/snyk-maven-plugin/pull/45

**Comment by lili2311** [comment]
Closing to

**Pull request closed without merging**
