### PR TITLE
feat: configure snyk-maven-plugin to read version plugin from settings.xml to avoid redundancy

### PR DESCRIPTION
**Pull request by sfat**
- [ ] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk-maven-plugin/blob/master/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

 #### What does this PR do?

 #### Where should the reviewer start?

 #### How should this be manually tested?

 #### Any background context you want to provide?

 #### What are the relevant tickets?

 #### Screenshots

 #### Additional questions

### CODE REVIEW

**Comment by sfat** [comment]
@lili2311 or @yuliabaron can you cherry pick this and merge it, please?
I think it will simplify things when bumping the version of the plugin.

**Comment by yuliabaron** [comment]
done https://github.com/snyk/snyk-maven-plugin/pull/48

I've just published the 1.2.3 version. I'll wait a bit with the next release, ok?

**Comment by sfat** [comment]
@yuliabaron ,
I think there is not need for a new bump of the version because it's not really something that has changed. It just affects the integration tests which I don't think it's relevant for the plugin itself besides some refactoring.
Or after a PR is merged, there is a need to bump the version?

**Comment by yuliabaron** [comment]
I need to update the version for the publishing. As we just merged few fixes and I published 1.2.3, I didn't bump the version for this one. I agree there's no need to publish this on its own

**Comment by sfat** [comment]
@yuliabaron can we close this? I think you committed in a different PR this already, right?

**Pull request closed without merging**
